name: nb_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - pip:
      - evidently==0.7.7
      - great-expectations==1.5.0
      - mlflow==2.22.1
      - numpy==1.26.4
      - pandas==1.3.5
      - pytest==8.4.0
      - dvc==3.59.1
      - scikit-learn==1.6.1
      - ydata-profiling==4.12.2
      