name: pipeline_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - pip:
     - mlflow==3.5.1
     - dvc==3.60.0
     - hydra-core==1.3.2
     - poetry==2.1.3

      