# Python version required to run the project.
python: "3.11.6"
# Dependencies required to build packages. This field is optional.
build_dependencies:
  - pip
  - setuptools
  - wheel
# Dependencies required to run the project.
dependencies:
  - mlflow==2.20.3
  - scikit-learn==1.6.1
  - pandas==2.2.3