name: preprocessing_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - pip:
      - mlflow==3.5.1
      - pandas==2.3.3
      - dvc==3.60.1
      - colorlog==6.9.0
      - dist/salary_classifier-1.0.0-py3-none-any.whl
